<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="methods" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="methods" name="Testrunner2(failed)">
    <classes>
      <class name="com.vtiger.purchaseorder.CreatePOwithItemWOlistPriceTest">
        <methods>
          <include name="logout"/>
          <include name="closeBrowser"/>
          <include name="createPOwithItemWOlistPriceTest"/>
          <include name="login"/>
          <include name="openBrowser"/>
        </methods>
      </class> <!-- com.vtiger.purchaseorder.CreatePOwithItemWOlistPriceTest -->
      <class name="com.vtiger.purchaseorder.CreatePOwithMandatoryExceptItemTest">
        <methods>
          <include name="logout"/>
          <include name="closeBrowser"/>
          <include name="createPOwithMandatoryExceptItemTest"/>
          <include name="login"/>
          <include name="openBrowser"/>
        </methods>
      </class> <!-- com.vtiger.purchaseorder.CreatePOwithMandatoryExceptItemTest -->
    </classes>
  </test> <!-- Testrunner2(failed) -->
</suite> <!-- Failed suite [Suite] -->
